apiVersion: v1
kind: Pod
metadata:
  name: kuardapp
  labels:
    name: kuardapp
spec:
  containers:
    - name: kuardapp
      image: gcr.io/kuar-demo/kuard-amd64:1
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
      ports:
        - containerPort: 8080
